# -*- mode: Python -*-

def k8s_yaml_glob(*glob_patterns, **kwargs):
    """
    Create/apply list of Kubernetes YAML files matching the given glob patterns.
    """
    SEP = "|"
    IS_WINDOWS = True if os.name == "nt" else False
    python = 'py -3' if IS_WINDOWS else 'python3'

    for pat in glob_patterns:

        # Compose a short script to collect matches, format them and emit the formatted list.
        script = '\
            import glob; \
            matches=glob.glob("{pat}"); \
            formatted="{sep}".join(matches); \
            print(formatted) \
        '.format(pat=pat, sep=SEP).strip()

        # Run the script and capture the output.
        cmd = "{python} -c '{script}'".format(
            python=python, script=script,
        )
        output = str(local(command=cmd, quiet=False)).strip()

        # Split it up and apply the YAML files.
        yaml_paths = output.split(SEP)
        k8s_yaml(yaml_paths, **kwargs)
